<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Task.Monitor.System.Services.Tests" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Task.Monitor.Cli.Utils\Task.Monitor.Cli.Utils.csproj" />
      <ProjectReference Include="..\Task.Monitor.Interop.Mach\Task.Monitor.Interop.Mach.csproj" />
      <ProjectReference Include="..\Task.Monitor.Interop.Win32\Task.Monitor.Interop.Win32.csproj" />
    </ItemGroup>

</Project>
