<Project>
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
      <DefineConstants>$(DefineConstants);__WIN32__</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('MacOS'))">
      <DefineConstants>$(DefineConstants);__APPLE__</DefineConstants>
  </PropertyGroup>
</Project>