<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Task.Monitor</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Task.Monitor.System\Task.Monitor.System.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Task.Monitor.Tests" />
    </ItemGroup>

</Project>
