<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Task.Monitor</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Task.Monitor.System\Task.Monitor.System.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Task.Monitor.Tests" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\Themes\Classic HTop.theme" />
      <None Remove="Assets\Themes\MSDOS.theme" />
      <EmbeddedResource Include="Assets\Themes\MSDOS.theme" />
      <None Remove="Assets\Themes\Github Dark.theme" />
      <EmbeddedResource Include="Assets\Themes\Github Dark.theme" />
      <None Remove="Assets\Themes\Tokyo Night.theme" />
      <EmbeddedResource Include="Assets\Themes\Tokyo Night.theme" />
      <None Remove="Assets\Themes\Taskmon Default.theme" />
      <EmbeddedResource Include="Assets\Themes\Taskmon Default.theme" />
      <None Remove="Assets\Themes\One Dark Pro.theme" />
      <EmbeddedResource Include="Assets\Themes\One Dark Pro.theme" />
      <None Remove="Assets\Themes\Dracula Official.theme" />
      <EmbeddedResource Include="Assets\Themes\Dracula Official.theme" />
      <None Remove="Assets\Themes\Catppuccin.theme" />
      <EmbeddedResource Include="Assets\Themes\Catppuccin.theme" />
      <None Remove="Assets\Themes\Ayu.theme" />
      <EmbeddedResource Include="Assets\Themes\Ayu.theme" />
      <None Remove="Assets\Themes\Monochrome.theme" />
      <EmbeddedResource Include="Assets\Themes\Monochrome.theme" />
      <None Remove="Assets\Themes\Amber.theme" />
      <EmbeddedResource Include="Assets\Themes\Amber.theme" />
      <None Remove="Assets\Themes\Green.theme" />
      <EmbeddedResource Include="Assets\Themes\Green.theme" />
      <None Remove="Assets\Layouts\All Charts.layout" />
      <EmbeddedResource Include="Assets\Layouts\All Charts.layout" />
      <None Remove="Assets\Layouts\All Charts Large.layout" />
      <EmbeddedResource Include="Assets\Layouts\All Charts Large.layout" />
      <None Remove="Assets\Layouts\Cpu and Memory.layout" />
      <EmbeddedResource Include="Assets\Layouts\Cpu and Memory.layout" />
      <None Remove="Assets\Layouts\Cpu and Memory Large.layout" />
      <EmbeddedResource Include="Assets\Layouts\Cpu and Memory Large.layout" />
      <None Remove="Assets\Layouts\Disk Read and Write Bytes.layout" />
      <EmbeddedResource Include="Assets\Layouts\Disk Read and Write Bytes.layout" />
      <None Remove="Assets\Layouts\Disk Read and Write Bytes Large.layout" />
      <EmbeddedResource Include="Assets\Layouts\Disk Read and Write Bytes Large.layout" />
      <None Remove="Assets\Layouts\Gpu and Gpu Memory.layout" />
      <EmbeddedResource Include="Assets\Layouts\Gpu and Gpu Memory.layout" />
      <None Remove="Assets\Layouts\Gpu and Gpu Memory Large.layout" />
      <EmbeddedResource Include="Assets\Layouts\Gpu and Gpu Memory Large.layout" />
      <None Remove="Assets\Layouts\Network Send and Receive Bytes.layout" />
      <EmbeddedResource Include="Assets\Layouts\Network Send and Receive Bytes.layout" />
      <None Remove="Assets\Layouts\Network Send and Receive Bytes Large.layout" />
      <EmbeddedResource Include="Assets\Layouts\Network Send and Receive Bytes Large.layout" />
    </ItemGroup>

</Project>
