[Alien Blood]
colour-mode=truecolour

background=#0f1610
background-highlight=#1d4125

col-cmd-normal-user-space=#327f77
col-cmd-low-priority=#10b981
col-cmd-high-cpu=#b082d1
col-cmd-io-bound=#dff0e6
col-cmd-script=#dff0e6
col-user-current-non-root=#b082d1
col-user-other-non-root=#b082d1
col-user-system=#73fa91
col-user-root=#73fa91

command-foreground=#717f24
command-background=#121d18

delta-highlight-colour=#bda25c

error=#a6423f

foreground=#717f24
foreground-highlight=#73fa91

menubar-foreground=#717f24
menubar-background=#121d18

range-high-background=#b082d1
range-low-background=#10b981
range-mid-background=#ffd085
range-high-foreground=#000000
range-low-foreground=#000000
range-mid-foreground=#000000

header-background=#121d18
header-foreground=#717f24
