[Amber]
colour-mode=indexed

background=transparent
background-highlight=#FFFF00

col-cmd-normal-user-space=#ff7000
col-cmd-low-priority=#808000
col-cmd-high-cpu=#FF0000
col-cmd-io-bound=#808000
col-cmd-script=#FFFF00
col-user-current-non-root=#FFFF00
col-user-other-non-root=#FFFF00
col-user-system=#ffffff
col-user-root=#ffffff

command-foreground=#000000
command-background=#808000

delta-highlight-colour=#ff7000

error=#FF0000

foreground=#FFFF00
foreground-highlight=#000000

menubar-foreground=#000000
menubar-background=#808000

range-high-background=#ff7000
range-low-background=#f9c87c
range-mid-background=#ffac4a
range-high-foreground=#000000
range-low-foreground=#000000
range-mid-foreground=#000000

header-background=#808000
header-foreground=#000000
