[Ayu]
colour-mode=indexed

background=transparent
background-highlight=#3b5070

col-cmd-normal-user-space=#59a6e0
col-cmd-low-priority=#0000FF
col-cmd-high-cpu=#ffa759
col-cmd-io-bound=#2b7489
col-cmd-script=#e3b341
col-user-current-non-root=#95e6cb
col-user-other-non-root=#bae67e
col-user-system=#ffa759
col-user-root=#ffd580

command-foreground=#bae67e
command-background=#1f2430

delta-highlight-colour=#ffa759

error=#db61a2

foreground=#bae67e
foreground-highlight=#95e6cb

menubar-foreground=#bae67e
menubar-background=#1f2430

range-high-background=#ffa759
range-low-background=#bae67e
range-mid-background=#ffa759
range-high-foreground=#000000
range-low-foreground=#000000
range-mid-foreground=#000000

header-background=#1f2430
header-foreground=#bae67e
