[Catppuccin]
colour-mode=indexed

background=transparent
background-highlight=#3b5070

col-cmd-normal-user-space=#89b4fa
col-cmd-low-priority=#0000FF
col-cmd-high-cpu=#000000
col-cmd-io-bound=#2b7489
col-cmd-script=#e3b341
col-user-current-non-root=#cdd6f4
col-user-other-non-root=#a6e3a1
col-user-system=#cba6f7
col-user-root=#89b4fa

command-foreground=#a6e3a1
command-background=#1e1e2e

delta-highlight-colour=#fab387

error=#db61a2

foreground=#a6e3a1
foreground-highlight=#eba0ac

menubar-foreground=#a6e3a1
menubar-background=#1e1e2e

range-high-background=#cba6f7
range-low-background=#a6e3a1
range-mid-background=#fab387
range-high-foreground=#000000
range-low-foreground=#000000
range-mid-foreground=#000000

header-background=#1e1e2e
header-foreground=#a6e3a1
