[Cobalt2]
colour-mode=indexed

background=transparent
background-highlight=#0050A4       

col-cmd-normal-user-space=#a5ff90  
col-cmd-low-priority=#ff628c       
col-cmd-high-cpu=#e1efff           
col-cmd-io-bound=#e1efff           
col-cmd-script=#80ffbb             
col-user-current-non-root=#0088ff  
col-user-other-non-root=#ff9d00    
col-user-system=#e1efff            
col-user-root=#e1efff              

command-foreground=#e1efff         
command-background=#193549         

delta-highlight-colour=#9effff     

error=#db61a2

foreground=#ffc600                 
foreground-highlight=#ffffff21     

menubar-foreground=#e1efff         
menubar-background=#193549         

range-high-background=#ba55d3      
range-low-background=#0088ff       
range-mid-background=#ff9d00       
range-high-foreground=#222222
range-low-foreground=#222222
range-mid-foreground=#222222

header-background=#193549        
header-foreground=#e1efff        
