[Cyberpunk 2077]
colour-mode=indexed

background=transparent
background-highlight=#6272A4       

col-cmd-normal-user-space=#FDF500  
col-cmd-low-priority=#37EBF3       
col-cmd-high-cpu=#37EBF3           
col-cmd-io-bound=#0E79B2           
col-cmd-script=#E455AE             
col-user-current-non-root=#6272A4  
col-user-other-non-root=#2CF6B3    
col-user-system=#2CF6B3            
col-user-root=#2CF6B3              

command-foreground=#000000         
command-background=#37EBF350       

delta-highlight-colour=#6272A4     

error=#db61a2

foreground=#E455AE                 
foreground-highlight=#ffffff      

menubar-foreground=#000000         
menubar-background=#37EBF350       

range-high-background=#37EBF3      
range-low-background=#6272A4       
range-mid-background=#4CAEDB       
range-high-foreground=#222222
range-low-foreground=#222222
range-mid-foreground=#222222

header-background=#37EBF350        
header-foreground=#000000          
