[Dracula Official]
colour-mode=indexed

background=transparent
background-highlight=#3b5070

col-cmd-normal-user-space=#50fa7b
col-cmd-low-priority=#0000FF
col-cmd-high-cpu=#ff79c6
col-cmd-io-bound=#bd93f9
col-cmd-script=#e3b341
col-user-current-non-root=#f8f8f2
col-user-other-non-root=#f1fa8c
col-user-system=#ff79c6
col-user-root=#50fa7b

command-foreground=#bd93f9
command-background=#282a36

delta-highlight-colour=#ffb86c

error=#db61a2

foreground=#f8f8f2
foreground-highlight=#ffb86c

menubar-foreground=#f1fa8c
menubar-background=#282a36

range-high-background=#bd93f9
range-low-background=#f1fa8c
range-mid-background=#ffb86c
range-high-foreground=#000000
range-low-foreground=#000000
range-mid-foreground=#000000

header-background=#282a36
header-foreground=#f1fa8c
