[Green Beautiful 2]
colour-mode=indexed

background=transparent
background-highlight=#228b22

col-cmd-normal-user-space=#FDFD96
col-cmd-low-priority=#115d33
col-cmd-high-cpu=#000000
col-cmd-io-bound=#c3f550
col-cmd-script=#93dc5c
col-user-current-non-root=#8dd06c
col-user-other-non-root=#196a0b
col-user-system=#ccff00
col-user-root=#ccff00

command-foreground=#ba55d3
command-background=#115d33

delta-highlight-colour=#FFB347

error=#db61a2

foreground=#228b22
foreground-highlight=#e6edf3

menubar-foreground=#ba55d3
menubar-background=#115d33

range-high-background=#4cbb17
range-low-background=#8dd06c
range-mid-background=#70c247
range-high-foreground=#000000
range-low-foreground=#000000
range-mid-foreground=#000000

header-background=#115d33
header-foreground=#ba55d3

