;=============================================================================
; Task Monitor (taskmon) - Built-in Theme
;=============================================================================
; IMPORTANT:
; Any modifications to default/shipped theme files will be reset automatically
; when taskmon runs or updates.
;
; How to create a custom theme:
;   Step 1: Copy this file to a new name (e.g. "Tokyo Night Custom.theme").
;   Step 2: Rename the header "[Tokyo Night]" to "[Tokyo Night Custom]".
;   Step 3: Customize color hex values (#RRGGBB).
;=============================================================================
[Green Beautiful 2]
colour-mode=indexed

control.background=transparent
control.background.highlight.focused=#228b22
control.background.highlight.inactive=#708090
control.foreground=#228b22
control.foreground.highlight.focused=#e6edf3
control.foreground.highlight.inactive=#e6edf3
control.border=#228b22
control.border.focused=#ba55d3

chart.background=transparent
chart.borderforeground=#228b22
chart.borderbackground=transparent
chart.yaxis=#FDFD96
chart.title=#228b22
chart.grid=#A9A9A9
chart.range.low.background=#8dd06c
chart.range.low.foreground=#000000
chart.range.mid.background=#70c247
chart.range.mid.foreground=#000000
chart.range.high.background=#4cbb17
chart.range.high.foreground=#000000

metre.background=transparent
metre.foreground=#228b22
metre.borderforeground=#228b22
metre.borderbackground=transparent

listview.background=transparent
listview.foreground=#228b22
listview.borderforeground=#228b22
listview.borderbackground=transparent
listview.header.background=#115d33
listview.header.foreground=#ba55d3

performance.panel.background=transparent
performance.panel.foreground=#228b22
performance.panel.titlebar.background=#115d33
performance.panel.titlebar.foreground=#ba55d3
performance.cpu.kernel=#4cbb17
performance.cpu.user=#FDFD96
performance.memory.inuse=#4cbb17
performance.memory.modified=#FDFD96
performance.memory.standby=#70c247
performance.memory.free=#8dd06c

property.key=#228b22
property.value=#228b22

process.list.normaluserspace=#FDFD96
process.list.lowpriority=#115d33
process.list.highcpu=#4cbb17
process.list.iobound=#c3f550
process.list.script=#93dc5c
process.list.user.currentnonroot=#8dd06c
process.list.user.othernonroot=#196a0b
process.list.user.system=#ccff00
process.list.user.root=#ccff00
process.list.deltahighlight=#FFB347

heatmap.size.small=#8dd06c
heatmap.size.mid=#70c247
heatmap.size.large=#4cbb17
heatmap.state.scanning=#000000
heatmap.state.completed=#000000
heatmap.state.faulted=#000000

app.error=#db61a2

menubar.foreground=#ba55d3
menubar.background=#115d33

command.foreground=#ba55d3
command.background=#115d33
