[macOS Classic]
colour-mode=indexed

background=transparent
background-highlight=#004a9e

col-cmd-normal-user-space=#ffffff
col-cmd-low-priority=#b5cea8
col-cmd-high-cpu=#ff453a
col-cmd-io-bound=#ffd60a
col-cmd-script=#b5cea8
col-user-current-non-root=#76BA53
col-user-other-non-root=#76BA53
col-user-system=#ce9178
col-user-root=#ce9178

command-foreground=#d4d4d4
command-background=#1e1e1e

delta-highlight-colour=#E1D797
;delta-highlight-colour=#ffff00

error=#ff453a

foreground=#E19773
;foreground=AC98AD
foreground-highlight=#ffffff

menubar-foreground=#858585
menubar-background=#1e1e1e

range-high-background=#AC98AD
range-low-background=#76BA53
range-mid-background=#ffd60a
range-high-foreground=#000000
range-low-foreground=#000000
range-mid-foreground=#000000

header-background=#1e1e1e
header-foreground=#858585
