[Monochrome]
colour-mode=indexed

background=transparent
background-highlight=#808080

col-cmd-normal-user-space=#ffffff
col-cmd-low-priority=#ffffff
col-cmd-high-cpu=#ffffff
col-cmd-io-bound=#ffffff
col-cmd-script=#ffffff
col-user-current-non-root=#ffffff
col-user-other-non-root=#ffffff
col-user-system=#ffffff
col-user-root=#ffffff

command-foreground=#000000
command-background=#c0c0c0

delta-highlight-colour=#ffffff

error=#ffffff

foreground=#ffffff
foreground-highlight=#ffffff

menubar-foreground=#000000
menubar-background=#c0c0c0

range-high-background=#c0c0c0
range-low-background=#c0c0c0
range-mid-background=#c0c0c0
range-high-foreground=#808080
range-low-foreground=#808080
range-mid-foreground=#808080

header-background=#c0c0c0
header-foreground=#000000
