[MSDOS]
colour-mode=truecolour

background=#000080
background-highlight=#00FFFF

col-cmd-normal-user-space=#FFFF00
col-cmd-low-priority=#C0C0C0
col-cmd-high-cpu=#000000
col-cmd-io-bound=#FF0000
col-cmd-script=#FFFF00
col-user-current-non-root=#C0C0C0
col-user-other-non-root=#808080
col-user-system=#FFFF00
col-user-root=#FF0000

command-foreground=#FFFF00
command-background=#008080

delta-highlight-colour=#FFFF00

error=#FF0000

foreground=#808080
foreground-highlight=#000000

menubar-foreground=#FFFF00
menubar-background=#008080

range-high-background=#FF0000
range-low-background=#00FF00
range-mid-background=#FFFF00
range-high-foreground=#000000
range-low-foreground=#000000
range-mid-foreground=#000000

header-background=#008080
header-foreground=#FFFF00
