[One Dark Pro]
colour-mode=indexed

background=transparent
background-highlight=##3b5070

col-cmd-normal-user-space=#61afef
col-cmd-low-priority=#0000FF
col-cmd-high-cpu=#c678dd
col-cmd-io-bound=#2b7489
col-cmd-script=#e3b341
col-user-current-non-root=#61afef
col-user-other-non-root=#98c379
col-user-system=#c678dd
col-user-root=#e06c75

command-foreground=#98c379
command-background=#282c34

delta-highlight-colour=#d19a66

error=#db61a2

foreground=#98c379
foreground-highlight=#e06c75

menubar-foreground=#98c379
menubar-background=#282c34

range-high-background=#c678dd
range-low-background=#98c379
range-mid-background=#d19a66
range-high-foreground=#222222
range-low-foreground=#222222
range-mid-foreground=#222222

header-background=#282c34
header-foreground=#98c379
