[Shades of Purple]
colour-mode=indexed

background=transparent
background-highlight=#B362FF       

col-cmd-normal-user-space=#A5FF90    
col-cmd-low-priority=#FF628C         
col-cmd-high-cpu=#E1EFFF             
col-cmd-io-bound=#E1EFFF             
col-cmd-script=#80FFBB               
col-user-current-non-root=#B362FF    
col-user-other-non-root=#FF9D00      
col-user-system=#FFEE80              
col-user-root=#FFEE80                

command-foreground=#FFFFFF         
command-background=#222244         

delta-highlight-colour=#9EFFFF     

error=#db61a2

foreground=#B362FF                 
foreground-highlight=#FFFFFF0D     

menubar-foreground=#FFFFFF         
menubar-background=#222244         

range-high-background=#B362FF      
range-low-background=#A5FF90       
range-mid-background=#FF9D00       
range-high-foreground=#222222
range-low-foreground=#222222
range-mid-foreground=#222222

header-background=#222244          
header-foreground=#FFFFFF          
