[Taskmon Default]
colour-mode=indexed

background=transparent
background-highlight=#00FFFF

col-cmd-normal-user-space=#00FF00
col-cmd-low-priority=#0000FF
col-cmd-high-cpu=#FF0000
col-cmd-io-bound=#00FFFF
col-cmd-script=#FFFF00
col-user-current-non-root=#00FF00
col-user-other-non-root=#FF00FF
col-user-system=#C0C0C0
col-user-root=#FFFFFF

command-foreground=#000000
command-background=#00FFFF

delta-highlight-colour=#808000

error=#FF0000

foreground=#FFFFFF
foreground-highlight=#000000

menubar-foreground=#FFFFFF
menubar-background=#000080

range-high-background=#FF0000
range-low-background=#00FF00
range-mid-background=#FFFF00
range-high-foreground=#000000
range-low-foreground=#000000
range-mid-foreground=#000000

header-background=#008000
header-foreground=#000000
