[Tokyo Night]
colour-mode=indexed

background=transparent
background-highlight=##3b5070

col-cmd-normal-user-space=#9ece6a
col-cmd-low-priority=#0000FF
col-cmd-high-cpu=#000000
col-cmd-io-bound=#2b7489
col-cmd-script=#e3b341
col-user-current-non-root=#a9b1d6
col-user-other-non-root=#9ece6a
col-user-system=#bb9af7
col-user-root=#7aa2f7

command-foreground=#9ece6a
command-background=#1a1b26

delta-highlight-colour=#ff9e64

error=#db61a2

foreground=#a9b1d6
foreground-highlight=#c0caf5

menubar-foreground=#9ece6a
menubar-background=#1a1b26

range-high-background=#bb9af7
range-low-background=#9ece6a
range-mid-background=#ff9e64
range-high-foreground=#000000
range-low-foreground=#000000
range-mid-foreground=#000000

header-background=#1a1b26
header-foreground=#9ece6a
